version: "3.9"

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - my_projects_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my_projects_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  my_projects_network:
    external: true
